[package]
name = "search_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.176", features=["derive"]}
serde_json = "1.0.99"

tiny_http = "0.12.0"
xml-rs = "0.8.14"
